/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pengelolaan_krs;

/**
 *
 * @author IRFAN HIDAYAT
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMhs = new javax.swing.JButton();
        btKrs = new javax.swing.JButton();
        btMatkul = new javax.swing.JButton();
        btSpp = new javax.swing.JButton();
        btKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btMhs.setBackground(new java.awt.Color(0,0,0,0));
        btMhs.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        btMhs.setForeground(new java.awt.Color(255, 255, 255));
        btMhs.setBorderPainted(false);
        btMhs.setContentAreaFilled(false);
        btMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMhsActionPerformed(evt);
            }
        });
        getContentPane().add(btMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 125, 190, 65));

        btKrs.setBackground(new java.awt.Color(0,0,0,0));
        btKrs.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        btKrs.setForeground(new java.awt.Color(255, 255, 255));
        btKrs.setBorderPainted(false);
        btKrs.setContentAreaFilled(false);
        btKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKrsActionPerformed(evt);
            }
        });
        getContentPane().add(btKrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 125, 190, 65));

        btMatkul.setBackground(new java.awt.Color(0,0,0,0));
        btMatkul.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        btMatkul.setForeground(new java.awt.Color(255, 255, 255));
        btMatkul.setBorderPainted(false);
        btMatkul.setContentAreaFilled(false);
        btMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMatkulActionPerformed(evt);
            }
        });
        getContentPane().add(btMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 263, 190, 65));

        btSpp.setBackground(new java.awt.Color(0,0,0,0));
        btSpp.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        btSpp.setForeground(new java.awt.Color(255, 255, 255));
        btSpp.setBorderPainted(false);
        btSpp.setContentAreaFilled(false);
        btSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSppActionPerformed(evt);
            }
        });
        getContentPane().add(btSpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 263, 190, 65));

        btKembali.setBackground(new java.awt.Color(255, 51, 102));
        btKembali.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        btKembali.setForeground(new java.awt.Color(255, 255, 255));
        btKembali.setText("Keluar");
        btKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMhsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new pengelolaan_krs.data_mhs().setVisible(true);
    }//GEN-LAST:event_btMhsActionPerformed

    private void btKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKrsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new pengelolaan_krs.data_krs().setVisible(true);
    }//GEN-LAST:event_btKrsActionPerformed

    private void btMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMatkulActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new pengelolaan_krs.data_matkul().setVisible(true);
    }//GEN-LAST:event_btMatkulActionPerformed

    private void btSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSppActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new pengelolaan_krs.data_spp().setVisible(true);
    }//GEN-LAST:event_btSppActionPerformed

    private void btKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKembali;
    private javax.swing.JButton btKrs;
    private javax.swing.JButton btMatkul;
    private javax.swing.JButton btMhs;
    private javax.swing.JButton btSpp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
